"""Render the approved interactive field guide from the canonical essay source."""
import re
import json
import html
from datetime import datetime
from site_chrome import SOCIAL


def render_principles(fields, source):
    items=[]
    for n,title,body,q in re.findall(r'<h3 id="p(\d+)"><span class="pnum">\d+</span>(.*?)</h3>\s*<p>(.*?)</p>\s*<div class="diag"><b>The test</b>(.*?)</div>',source,re.S):
     items.append(dict(n=int(n),title=title,body=body,q=q))
    assert len(items)==12
    short=['Name the outcome. Name its owner.','Responsibility needs decision rights.','Confidence must be re-earned.','Let proof release the next investment.','Define the boundary before granting autonomy.','A control belongs in the path of action.','Share the foundation. Own the result.','Value depends on how people work.','Match the commitment to the evidence.','Make uncertainty visible early.','Data readiness sets the starting line.','Set the passing standard before launch.']
    groups=[('Business value',[1,4,8]),('Authority & ownership',[2,7,10]),('Evidence & readiness',[3,11,12]),('Operating boundaries',[5,6,9])]
    maphtml=''.join('<div class="map-group"><h3><span>0'+str(i+1)+'</span>'+name+'</h3>'+''.join(f'<a href="#principle-{n}" class="map-tile" data-map="{n}"><span class="tile-number">{n:02}</span><span>{items[n-1]["title"]}</span><span class="tile-arrow" aria-hidden="true">↗</span></a>' for n in ns)+'</div>' for i,(name,ns) in enumerate(groups))
    rail=''.join(f'<a href="#principle-{p["n"]}" data-rail="{p["n"]}"><span>{p["n"]:02}</span>{p["title"]}</a>' for p in items)
    diagrams={
    4:'''<figure class="mini-diagram"><figcaption>Investment follows evidence</figcaption><div class="gate-flow"><span>Bounded test<small>Agree the baseline</small></span><i>→</i><span class="gate">Evidence gate<small>Review the result</small></span><i>→</i><span>Next investment<small>Scale, adapt, or stop</small></span></div></figure>''',
    5:'''<figure class="mini-diagram"><figcaption>Define the agent's authority</figcaption><div class="boundary"><div><span class="mono">WITHIN THE BOUNDARY</span><b>Read approved sources</b><b>Prepare a draft</b></div><div class="human-gate"><span class="mono">HUMAN APPROVAL</span><b>Make a commitment</b><b>Take consequential action</b></div></div><p class="diagram-note">Illustrative customer-service design. Permissions depend on the workflow.</p></figure>''',
    7:'''<figure class="mini-diagram"><figcaption>One foundation. Distributed accountability.</figcaption><div class="unit-row"><span>Customer service<small>Owns its outcomes</small></span><span>Operations<small>Owns its outcomes</small></span><span>Commercial<small>Owns its outcomes</small></span></div><div class="platform">Shared platform · identity · evaluation · standards</div></figure>'''
    }
    sections=''
    for p,takeaway in zip(items,short):
     n=p['n'];sections+=f'''<section class="principle" id="principle-{n}" data-principle="{n}" aria-labelledby="title-{n}"><span id="p{n}" class="legacy-anchor" aria-hidden="true"></span><div class="principle-heading"><span class="big-number">{n:02}</span><div><p class="eyebrow">PRINCIPLE {n:02} / 12</p><h3 id="title-{n}">{p['title']}</h3><p class="takeaway">{takeaway}</p></div></div><p class="explanation">{p['body']}</p>{diagrams.get(n,'')}<div class="question-panel"><p class="eyebrow">ASK YOUR LEADERSHIP TEAM</p><p>{p['q']}</p><div class="answer-buttons" role="group" aria-label="Your reflection on principle {n}"><button type="button" data-answer="clear" data-n="{n}" aria-pressed="false">We can answer this <span aria-hidden="true">✓</span></button><button type="button" data-answer="discuss" data-n="{n}" aria-pressed="false">Needs discussion <span aria-hidden="true">＋</span></button></div></div></section>'''
    hero_svg='''<svg viewBox="0 0 540 430" fill="none" aria-hidden="true"><defs><pattern id="grid" width="24" height="24" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r="1" fill="#bfd0d8"/></pattern><linearGradient id="wire"><stop stop-color="#acc1cd"/><stop offset="1" stop-color="#25465b"/></linearGradient></defs><rect width="540" height="430" fill="url(#grid)"/><g stroke="url(#wire)" stroke-width="1.5"><path d="M110 82H220Q270 82 270 132V178M430 82H320Q270 82 270 132"/><path d="M110 330H220Q270 330 270 280V242M430 330H320Q270 330 270 280"/><path d="M110 160H185Q220 160 240 185M430 160H355Q320 160 300 185M110 252H185Q220 252 240 227M430 252H355Q320 252 300 227"/></g><g class="diagram-pulse" stroke="#6f8fa2" stroke-width="1"><circle cx="270" cy="210" r="70"/><circle cx="270" cy="210" r="91" opacity=".45"/></g><circle cx="270" cy="210" r="47" fill="#25465b"/><text x="270" y="207" text-anchor="middle" fill="white" font-family="IBM Plex Sans,sans-serif" font-size="16">THE</text><text x="270" y="228" text-anchor="middle" fill="white" font-family="IBM Plex Sans,sans-serif" font-size="16">DECISION</text><g fill="#f8fafb" stroke="#adc1cd"><rect x="40" y="62" width="142" height="40" rx="5"/><rect x="358" y="62" width="142" height="40" rx="5"/><rect x="40" y="140" width="142" height="40" rx="5"/><rect x="358" y="140" width="142" height="40" rx="5"/><rect x="40" y="232" width="142" height="40" rx="5"/><rect x="358" y="232" width="142" height="40" rx="5"/><rect x="40" y="310" width="142" height="40" rx="5"/><rect x="358" y="310" width="142" height="40" rx="5"/></g><g fill="#25465b" font-family="JetBrains Mono,monospace" font-size="11" text-anchor="middle"><text x="111" y="87">OUTCOME</text><text x="429" y="87">AUTHORITY</text><text x="111" y="165">EVIDENCE</text><text x="429" y="165">OWNERSHIP</text><text x="111" y="257">VALUE</text><text x="429" y="257">BOUNDARIES</text><text x="111" y="335">READINESS</text><text x="429" y="335">REVIEW</text></g><circle class="signal" r="4" fill="#25465b"><animateMotion dur="5s" repeatCount="indefinite" path="M110 82H220Q270 82 270 132V163"/></circle></svg>'''
    data_json=json.dumps([{k:v for k,v in p.items() if k!='body'} for p in items]).replace('</', '<'+chr(92)+'/')
    intro=source.split('<div class="fp-index">',1)[0].strip()
    closing=source.split('<h3>When principles conflict</h3>',1)[1]
    context=intro+'<h3>When principles conflict</h3>'+closing
    page=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{html.escape(fields["title"])} — Alphaworx Insights</title><meta name="description" content="{html.escape(fields["excerpt"], quote=True)}"><link rel="canonical" href="https://alphaworx.io/blog/{fields["slug"]}.html">{SOCIAL}<link rel="icon" href="/assets/mark.png"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600&family=Instrument+Sans:wght@400;500;600&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet"><link rel="stylesheet" href="/assets/principles-guide.css?v=1"></head><body>
    <a class="skip" href="#main">Skip to field guide</a><header><a class="brand" href="/"><img src="/assets/mark.png" alt="" width="28" height="28">ALPHAWORX<span>.IO</span></a><a class="preview-label" href="/blog/">← ALL INSIGHTS</a><a class="header-link" href="#agenda">Your discussion agenda <span id="header-count">0</span></a><div class="reading-progress" aria-hidden="true"><span id="progress"></span></div></header>
    <main id="main"><section class="hero shell"><div class="hero-copy"><p class="eyebrow line">ALPHAWORX INSIGHTS / EXECUTIVE FIELD GUIDE</p><h1>Twelve principles.<br>A better way<br>to decide.</h1><p class="hero-sub">The first principles of enterprise AI strategy—made practical for the decisions in front of you.</p><div class="byline"><span>{html.escape(fields.get("author", "Alphaworx Insights"))}</span><span>{datetime.strptime(fields["date"], "%Y-%m-%d").strftime("%B %Y")}</span><span>12 principles</span></div><div class="hero-actions"><a class="primary" href="#scenario">Start with a decision <span>↗</span></a><a class="text-link" href="#principle-map">Explore the principles ↓</a></div></div><figure class="hero-art">{hero_svg}<figcaption><span class="tiny-square"></span>Many considerations. One accountable decision.</figcaption></figure></section>
    <div class="chapter-strip shell"><span><b>01</b> Face a decision</span><i>→</i><span><b>02</b> Explore the principles</span><i>→</i><span><b>03</b> Take the questions to your team</span></div>
    <section class="scenario shell" id="scenario"><div class="section-intro"><p class="eyebrow line">A DECISION UNDER PRESSURE</p><h2>The demo works.<br>Monday’s decision is harder.</h2><p>Step into a fictional Meridian Industrial Group leadership meeting. Choose a starting position, then examine the tradeoff.</p></div><div class="scenario-board"><div class="scenario-meta"><span class="mono">MERIDIAN INDUSTRIAL GROUP</span><span class="scenario-badge">Fictional scenario</span></div><div class="scenario-brief"><span class="memo-line">FROM THE CEO / CUSTOMER SERVICE</span><blockquote>“Our competitor just launched an AI agent.<br>Can we have ours live in 30 days?”</blockquote><p>The prototype answers routine questions. Production permissions, an accountable owner, and a passing evaluation standard are still undecided.</p></div><div class="decision-options" role="group" aria-label="Choose a starting decision"><button data-choice="launch" aria-pressed="false"><span>01 / ACCELERATE</span><b>Approve the rollout</b><small>Capture the early advantage.</small><i>↗</i></button><button data-choice="wait" aria-pressed="false"><span>02 / DEFER</span><b>Wait for certainty</b><small>Ask for a more complete plan.</small><i>↗</i></button><button data-choice="bound" aria-pressed="false"><span>03 / LIMIT THE SCOPE</span><b>Authorize a bounded pilot</b><small>Learn within explicit limits.</small><i>↗</i></button></div><div id="decision-response" class="decision-response" aria-live="polite"><span class="response-icon">↳</span><div><p class="eyebrow">YOUR FIRST MOVE</p><h3>What would you put your name to?</h3><p>Select a decision to see which principles it brings into focus.</p></div></div></div></section>
    <section class="map-section" id="principle-map"><div class="shell"><div class="map-heading"><div><p class="eyebrow line">THE DECISION FRAMEWORK</p><h2>Twelve principles.<br>Four connected lenses.</h2></div><p>Start where your next decision feels least clear. Each principle connects an operating rule to a question your leadership team should be able to answer.</p></div><div class="principle-map">{maphtml}</div><div class="map-footer"><span class="mono">SELECT A PRINCIPLE TO EXPLORE ↓</span><span>Your selections build a discussion agenda as you read.</span></div></div></section>
    <section class="reading-layout shell" id="read"><aside class="reading-rail"><p class="eyebrow">IN THIS FIELD GUIDE</p><nav aria-label="Principle chapters">{rail}</nav><a href="#agenda" class="rail-agenda">Your discussion agenda <span>↗</span></a></aside><div class="principles"><div class="reading-intro"><p class="eyebrow">THE PRINCIPLES IN PRACTICE</p><h2>Durable rules.<br>Practical questions.</h2><p>Use these as a decision filter. For each principle, consider one real initiative in your organization. Mark what you can answer and what deserves a conversation.</p><span class="session-note">Your reflections stay in this page and reset when you reload.</span></div>{sections}</div></section>
    <section class="agenda-section" id="agenda"><div class="shell agenda-layout"><div><p class="eyebrow line">TAKE IT INTO THE NEXT MEETING</p><h2>A more useful<br>leadership conversation.</h2><p>Your discussion agenda brings together the questions you marked for follow-up.</p><div class="agenda-counts"><span><b id="discuss-count">0</b> to discuss</span><span><b id="clear-count">0</b> clear answers</span><span><b id="unread-count">12</b> unreviewed</span></div><p class="session-note">A personal reflection tool, not an organizational assessment or maturity score.</p></div><div class="agenda-card"><div class="agenda-card-head"><span class="mono">YOUR DISCUSSION AGENDA</span><button class="reset" id="reset" type="button">Reset selections</button></div><div id="agenda-list"><p class="empty-agenda">Start with the questions that give you pause.</p><p class="empty-help">Choose “Needs discussion” beside any principle. Your selected questions will appear here, ready to bring to your team.</p><a href="#principle-1" class="text-link">Explore principle 01 ↗</a></div><div class="agenda-actions"><button class="primary" type="button" id="print-agenda" disabled>Print agenda ↗</button><button class="text-button" type="button" id="download-agenda" disabled>Download text ↓</button></div><p id="agenda-status" class="session-note" aria-live="polite"></p></div></div></section>
    <section class="closing shell"><p class="eyebrow">THE OPERATING HIERARCHY</p><p class="closing-statement">Principles shape judgment.<br>Accountability makes it real.</p><div class="hierarchy"><span><b>01 / Principles</b>How we judge</span><i>→</i><span><b>02 / Mandate</b>Who can decide</span><i>→</i><span><b>03 / Processes</b>How work happens</span><i>→</i><span><b>04 / Records</b>What the evidence shows</span></div><details class="essay-context" id="essay-context"><summary>Read the background and closing reflections <span>＋</span></summary><div class="context-body">{context}</div></details><div class="guide-contact"><p>Bring the questions that matter to your next AI decision.</p><a class="primary" href="/#contact">Discuss your AI strategy ↗</a></div></section></main>
    <footer class="shell"><span>© 2026 Alphaworx Ltd</span><a href="/blog/">All insights</a><a href="/privacy/">Privacy</a><button class="text-button" id="motion" aria-pressed="false">Pause motion</button></footer><script type="application/json" id="principle-data">{data_json}</script><script src="/assets/principles-guide.js?v=1" defer></script></body></html>'''
    return page
